services:
  authentication-service:
    image: alpine/java:21-jdk
    container_name: authentication-service
    hostname: authentication-service
    ports:
      - "8080:8080"
    volumes:
    - ./:/app
    working_dir: /app
    command: ./many spring-boot:run
    depends_on:
      - authentication-db
    networks:
      - auth-network
  
  authentication-db:
    image: postgres:13-alpine
    container_name: authentication-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: authenticationdb
    volumes:
      - authentication_db_data:/var/lib/postgresql/data
    networks:
      - auth-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ax@micro.kz
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "7313:80"
    depends_on:
      - authentication-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - auth-network
  
  # redis:
  #   image: redis:6.2.6-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - route for volume. don't forget to make it clear
  #   networks:
  #     - auth-network

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.7.1
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   networks:
  #     - auth-network

  # kafka:
  #   image: confluentinc/cp-kafka:7.7.1
  #   container_name: kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   networks:
  #     - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  authentication_db_data:
  pgadmin_data: